name: hmm_irregularity
channels:
  - defaults
dependencies:
  - pandas=2.2.3
  - python=3.11.11
  - r-base=4.3
  - r-dplyr=1.1.4
  - r-rstan=2.32.6
  - matplotlib
  - seaborn
  - conda-forge::r-codetools
